/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-dim": "#0c0e14",
        "error-container": "#8a1a1e",
        "surface-container": "#161922",
        "surface-bright": "#272c39",
        "on-tertiary-fixed": "#004931",
        "on-error": "#490006",
        "secondary": "#b3ccbf",
        "on-primary-fixed": "#002659",
        "outline": "#717583",
        "primary-dim": "#699cff",
        "inverse-surface": "#faf8ff",
        "inverse-on-surface": "#53555c",
        "on-tertiary-container": "#005e40",
        "on-secondary-container": "#90aa9d",
        "on-surface": "#e2e5f4",
        "on-primary-container": "#000311",
        "surface-container-low": "#11131a",
        "error": "#ff716c",
        "surface-container-lowest": "#000000",
        "tertiary-fixed": "#8bf8c4",
        "on-surface-variant": "#a7aab9",
        "outline-variant": "#444854",
        "primary": "#699cff",
        "tertiary-container": "#8bf8c4",
        "surface": "#0c0e14",
        "surface-tint": "#699cff",
        "secondary-dim": "#a5bfb2",
        "primary-fixed": "#a5c1ff",
        "secondary-fixed": "#dcf7e9",
        "inverse-primary": "#005bc4",
        "surface-variant": "#222631",
        "background": "#0c0e14",
        "primary-container": "#4388fd",
        "secondary-fixed-dim": "#cee9db",
        "on-primary": "#001e4a",
        "on-secondary-fixed": "#364d43",
        "on-secondary-fixed-variant": "#52695f",
        "tertiary-fixed-dim": "#7ce9b7",
        "secondary-container": "#132a21",
        "surface-container-highest": "#222631",
        "on-error-container": "#ff9993",
        "on-primary-fixed-variant": "#004292",
        "surface-container-high": "#1c1f29",
        "primary-fixed-dim": "#8fb3ff",
        "tertiary-dim": "#7ce9b7",
        "on-background": "#e2e5f4",
        "on-tertiary": "#006747",
        "on-secondary": "#2e453b",
        "tertiary": "#beffdc",
        "error-dim": "#c94947",
        "on-tertiary-fixed-variant": "#006948"
      },
      fontFamily: {
        "headline": ["Inter"],
        "display": ["Inter"],
        "body": ["Inter"],
        "label": ["Inter"]
      }
    },
  },
  plugins: [],
}
